import type { Metadata } from "next";

import "./globals.css";
import React from "react";
import Render from "./render";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Render>{children}</Render>
      </body>
    </html>
  );
}
